plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'fabric-loom' version "${loom_version}"
}

group = "com.github.mcjty"
version = project.version

base {
    archivesName = "${mod_id}-fabric-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(java_version))

if (System.getenv('BUILD_NUMBER') != null) {
    version += "-${System.getenv('BUILD_NUMBER')}"
}

repositories {
    mavenCentral()
    maven {
        name = 'ParchmentMC'
        url = 'https://maven.parchmentmc.org'
        content {
            includeGroup 'org.parchmentmc.data'
        }
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

tasks.withType(Jar).configureEach {
    includeEmptyDirs = false
}

loom {
    def aw = file("src/main/resources/META-INF/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    compileOnly 'com.google.code.findbugs:jsr305:3.0.2'
}

processResources {
    def expandProps = [
            'version'              : version,
            'mod_id'               : mod_id,
            'mod_name'             : mod_name,
            'minecraft_version'    : minecraft_version,
            'fabric_loader_version': fabric_loader_version,
            'java_version'         : java_version
    ]
    filesMatching('fabric.mod.json') {
        expand expandProps
    }
    inputs.properties(expandProps)
}

tasks.register('apiJar', Jar) {
    archiveClassifier = "api"
    from(sourceSets.main.output) {
        include "mcjty/lostcities/api/**"
    }
}

artifacts {
    archives apiJar
}

publishing {
    publications.create('mavenJava', MavenPublication) {
        from components.java
        artifact apiJar

        artifactId = mod_id
        pom {
            name = 'LostCities'
            description = 'Lost Cities'
            scm {
                url = 'https://github.com/McJtyMods/LostCities'
                connection = 'scm:git:git@github.com:McJtyMods/LostCities.git'
                developerConnection = 'scm:git:git@github.com:McJtyMods/LostCities.git'
            }
            issueManagement {
                system = 'github'
                url = 'https://github.com/McJtyMods/LostCities/issues'
            }
            licenses {
                license {
                    name = 'MIT'
                    distribution = 'repo'
                }
            }
            developers {
                developer {
                    id = 'McJty'
                    name = 'McJty'
                    roles = ['developer']
                }
            }
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                name = 'local'
                url = 'file://' + System.getenv('local_maven')
            }
        }
    }
}
